version: '3'

services:
  app:
    build:
      context: './avideo'
    container_name: avideo-server
    volumes:
      - "server_src:/opt/app/server"
    ports:
      - '8081:8081'

volumes:
  server_src:
    driver_opts:
      type: none
      device: ./avideo/server
      o: bind
